apiVersion: v1
kind: Service
metadata:
  name: task-app-svc
  namespace: task-app
spec:
  type: NodePort
  selector:
    app: task-app
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30080
